### PR TITLE
Ruby Implementation

### PR DESCRIPTION
**Pull request by williamgrh**

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
_Almost_ ready for commit. A few questions & issues...
- Why `.vs/config/applicationhost.config`?
- Last solution in Ruby/Hashes doesn't work - you can't add ints and strings...
  - How much did you test the code snippets?
- Did you pull code from the [ruby branch](https://github.com/JoshuaKGoldberg/HighSchoolHacking/tree/ruby)? It looks like you did (which is preferable!).
- You had mentioned Prism isn't highlighting. That should probably be fixed, but it can be a separate bug after merging the PR.

**Comment by williamgrh** [comment]
Should be set now
- Fixed
- Fixed
- Yes
- Highlighting now works
- Added some more info to For Loops because of the way Ruby does loops

**Comment by JoshuaKGoldberg** [comment]
Close to perfect. Can you remove `.vs/config/applicationhost.config`? (and add the .vs folder to gitignore?)

:)

**Comment by williamgrh** [comment]
Did that do it?

**Comment by JoshuaKGoldberg** [comment]
Seems legit!

**Pull request merged**
